### ISSUE TITLE
批量检测到最后会卡死

### ISSUE THREAD

**Issue by EasyRain** [GenesisAN/KKCardModCheck#1]
![image](https://user-images.githubusercontent.com/46843500/212606110-5045d3d5-0f62-411e-9f22-9266d0ebc699.png)
如图，文件夹内就3张卡，单张检测都是一瞬间完成的，合一起就会卡在最后一步

**Comment by EasyRain** [comment]
所有都会这样，我原先直接把整个chara文件夹扔进去，后来卡最后很久没反应，我还以为是卡太多检测很慢，然后我又试了试卡少点的文件夹，到最后还是卡住，最后选了个只有三张卡的文件夹检测，不出所料还是卡住，我又去试了试单张检测，三张卡都能瞬间检测完，放一起批量就不行，然后json暂时没法上传，我这会儿没在家，用的是zod上g大的整合包

**Comment by GenesisAN** [comment]
那只能等待你提供一下json文件后再做具体判断了，我先检查一下相关位置看看能否得出什么结论

**Comment by EasyRain** [comment]
我又试了下，卡在最后一步很久按了下esc之后就变成下图这样
![image](https://user-images.githubusercontent.com/46843500/212644693-22fbfa44-bf4e-4cc2-8305-43cd2c24f616.png)
很怪，我按了esc之后再重新检测3张卡的文件夹就一瞬间就出上图的提示(重新检测的没有按esc)，但是我换个多了几张卡的(6张)文件夹，又不行了，按esc之后再检测依旧卡死不出提示，然后这个检测完的怎么用怎么看我也用明白
[ModsInfo.txt](https://github.com/GenesisAN/KKCardModCheck/files/10424438/ModsInfo.txt)
github不能上传json文件只能改成txt了

**Comment by GenesisAN** [comment]
已经确定触发范围和具体方式了，目前在win11上会触发，实际上界面是加载了，但你要动一下反向键，才会刷新渲染。具体如何处理我还要研究一下。

**Comment by GenesisAN** [comment]
我已经发布了一个[新的提交](https://github.com/GenesisAN/KKCardModCheck/actions/runs/3937542726)尝试修复该问题，你可以在这里[下载](https://github.com/GenesisAN/KKCardModCheck/suites/10410646622/artifacts/514355178)新提交生成的应用程序。如果确认问题得到解决，我将会发布一个版本更新解决该问题。

**Comment by EasyRain** [comment]
![image](https://user-images.githubusercontent.com/46843500/212902640-b89edb80-40f4-4956-96f4-f343b2af77b7.png)
我试了下，这个ci版本能用了

**Comment by GenesisAN** [comment]
已在该次[提交1](https://github.com/GenesisAN/KKCardModCheck/commit/bef88b055d5295a38451d5f62e0dd55d4cd74171)和[提交2](https://github.com/GenesisAN/KKCardModCheck/commit/3608223165f8a3d2abbe09dbe533b8665a26d3b5)中修复该问题
