### ISSUE TITLE
生成modsinfo.json文件的时候直接卡停了

### ISSUE THREAD

**Issue by AnduinZZ** [GenesisAN/KKCardModCheck#4]
![image](https://github.com/GenesisAN/KKCardModCheck/assets/88436042/e5925a76-6a45-4255-a7ba-7e6da03298dc)

**Comment by AnduinZZ** [comment]
![image](https://github.com/GenesisAN/KKCardModCheck/assets/88436042/27a138ad-08c4-4d65-9b16-35295fbdac51)
![image](https://github.com/GenesisAN/KKCardModCheck/assets/88436042/76019e05-b7e1-43cc-9077-0f5111115faf)
![BMANN  Bowser Body Tattoo v1 0 0](https://github.com/GenesisAN/KKCardModCheck/assets/88436042/7618ca09-5640-438d-a6f8-a400d36fe494)

**Comment by GenesisAN** [comment]
能否提供一下该文件，我看看，你将该MOD打包为ZIP上传过来

**Comment by GenesisAN** [comment]
另外就是尝试移除该文件再试试
