### ISSUE TITLE
生成modsinfo.json文件卡停

### ISSUE THREAD

**Issue by Rio-III** [GenesisAN/KKCardModCheck#6]
![捕获](https://github.com/GenesisAN/KKCardModCheck/assets/153346056/fb551a2a-5dcd-4903-bf13-b61c491d537a)

**Comment by GenesisAN** [comment]
在最新发布的[v0.1.6](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.6)更新中已经修复该问题！
