### ISSUE TITLE
找不到Naier.Poltergeist，去网上查也没查到这个Mod

### ISSUE THREAD

**Issue by ZLK2333** [GenesisAN/KKCardModCheck#7]
![屏幕截图 2024-07-28 112245](https://github.com/user-attachments/assets/67f47bb3-2739-4f1a-b6bb-f9d3e9fd6f50)

**Comment by ZLK2333** [comment]
![屏幕截图 2024-07-28 112245]

**Comment by ZLK2333** [comment]
![屏幕截图 2024-07-28 112245](https://github.com/user-attachments/assets/248cfc8a-5ba6-47eb-b5b7-a4cf39378572)

**Comment by ZLK2333** [comment]
[2567/6539]Polti the poltergeist    com.Naier.Poltergeist    0.1.0              2024/07/28 11:25:46 打开zip失败:zip: e│║                                                                                                                    ║│
D:\Koikatu>pause══════════════════════════════════════════════════════════════════════════════════════════════════════╝│

**Comment by GenesisAN** [comment]
不好意思，我最近一直没空维护这个项目，我应该是没处理好这个Zip打开失败的逻辑，应该忽略继续遍历，项目。出于方便考虑，你可以直接先移除项目下的这个zip

**Comment by GenesisAN** [comment]
在最新发布的[v0.1.6](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.6)更新中已经修复该问题
