### ISSUE TITLE
生成mod数据文件失败

### ISSUE THREAD

**Issue by skyshall** [GenesisAN/KKCardModCheck#8]
![QQ图片20240907224057](https://github.com/user-attachments/assets/ff3b87c7-cc3e-425b-886a-948c138f26cb)
移除了这第2744个mod之后依然会显示同一种错误
![QQ截图20240907224700](https://github.com/user-attachments/assets/161eb6bb-636e-4b44-b30c-bab17a03495d)

**Comment by GenesisAN** [comment]
在最新发布的[v0.1.6](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.6)更新中已经修复该问题，多谢反馈！

**Comment by skyshall** [comment]
![QQ图片20240908150454](https://github.com/user-attachments/assets/bfc8d86a-2fe0-4b41-9ab2-22eab87c933b)
这一个mod读不了，不过现在不会在读不了的mod那里停下来了，生成速度也快了不少

**Comment by GenesisAN** [comment]
> ![QQ图片20240908150454](https://private-user-images.githubusercontent.com/180764321/365420134-bfc8d86a-2fe0-4b41-9ab2-22eab87c933b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU3ODI4NDEsIm5iZiI6MTcyNTc4MjU0MSwicGF0aCI6Ii8xODA3NjQzMjEvMzY1NDIwMTM0LWJmYzhkODZhLTJmZTAtNGI0MS05YWIyLTIyZWFiODdjOTMzYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOFQwODAyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NmNmZjM4NDUzMmQxMTZlYTI0M2I0NzFiYTExODRlNzIyZjEzNmNiNTU5ODA4OTVjMWE5ZmZlYjI5Y2Y1OGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oeIzb8y3tsOw9ecamor5jtP4u03GE_0cUhN3NcaGrz4) 这一个mod读不了，不过现在不会在读不了的mod那里停下来了，生成速度也快了不少

你可以把这个mod作为附件发过来看看，我看看怎么个事儿

**Comment by skyshall** [comment]
[读取失败文件.zip](https://github.com/user-attachments/files/16921526/default.zip)
mod在游戏内是正常运行的

**Comment by GenesisAN** [comment]
> [读取失败文件.zip](https://github.com/user-attachments/files/16921526/default.zip) mod在游戏内是正常运行的

OK，我搞明白了，里面的manifest.xml居然是utf16格式，导致我读取失败了，哭笑不得，默认情况下只能处理utf-8格式。晚点我会发布新的更新，让它能处理这种情况。

**Comment by GenesisAN** [comment]
OK，最新的[v0.1.7](https://github.com/GenesisAN/KKCardModCheck/releases/tag/v0.1.7)版本已经提交了。
